/* España · provincias (50) + ciudades autónomas (2) → municipios principales
 * Uso: selector de dos niveles en «Datos personales». Misma interfaz que el resto (MUNEA_REGIONS).
 * El segundo nivel recoge la capital de provincia y los municipios más poblados —no es el padrón
 * completo de 8.131 municipios: lo que no esté en la lista se escribe a mano con «Otro»,
 * para no publicar datos sin verificar (línea roja de honestidad de Munea).
 * coords = capital de provincia, para el tiempo y la calidad del aire (Open-Meteo, cobertura mundial).
 * Creado el 2026-07-31 tras la decisión de Edward: cada país con su propia lista administrativa. */
window.MUNEA_REGIONS = window.MUNEA_REGIONS || {};
window.MUNEA_REGIONS.ES = {
  countryCode: 'ES',
  tier1Key: 'profile.regionTier1Province',
  tier2Key: 'profile.regionTier2Municipality',
  otherKey: 'profile.regionOther',
  regions: {
    'A Coruña': { coords: [43.371, -8.396], cities: ['A Coruña', 'Santiago de Compostela', 'Ferrol', 'Narón', 'Oleiros'] },
    'Álava': { coords: [42.847, -2.673], cities: ['Vitoria-Gasteiz', 'Llodio', 'Amurrio', 'Salvatierra'] },
    'Albacete': { coords: [38.994, -1.858], cities: ['Albacete', 'Hellín', 'Villarrobledo', 'Almansa', 'La Roda'] },
    'Alicante': { coords: [38.345, -0.481], cities: ['Alicante', 'Elche', 'Torrevieja', 'Orihuela', 'Benidorm', 'Alcoy', 'Elda'] },
    'Almería': { coords: [36.834, -2.464], cities: ['Almería', 'Roquetas de Mar', 'El Ejido', 'Níjar', 'Adra'] },
    'Asturias': { coords: [43.362, -5.849], cities: ['Oviedo', 'Gijón', 'Avilés', 'Siero', 'Langreo', 'Mieres'] },
    'Ávila': { coords: [40.657, -4.700], cities: ['Ávila', 'Arévalo', 'Arenas de San Pedro', 'Las Navas del Marqués'] },
    'Badajoz': { coords: [38.879, -6.970], cities: ['Badajoz', 'Mérida', 'Don Benito', 'Almendralejo', 'Villanueva de la Serena'] },
    'Baleares': { coords: [39.570, 2.650], cities: ['Palma', 'Calvià', 'Ibiza', 'Manacor', 'Marratxí', 'Llucmajor', 'Mahón'] },
    'Barcelona': { coords: [41.385, 2.173], cities: ['Barcelona', "L'Hospitalet de Llobregat", 'Badalona', 'Terrassa', 'Sabadell', 'Mataró', 'Santa Coloma de Gramenet', 'Cornellà de Llobregat', 'Sant Cugat del Vallès', 'Manresa'] },
    'Burgos': { coords: [42.344, -3.697], cities: ['Burgos', 'Miranda de Ebro', 'Aranda de Duero', 'Briviesca'] },
    'Cáceres': { coords: [39.476, -6.372], cities: ['Cáceres', 'Plasencia', 'Navalmoral de la Mata', 'Coria', 'Trujillo'] },
    'Cádiz': { coords: [36.527, -6.289], cities: ['Cádiz', 'Jerez de la Frontera', 'Algeciras', 'San Fernando', 'El Puerto de Santa María', 'Chiclana de la Frontera', 'La Línea de la Concepción'] },
    'Cantabria': { coords: [43.463, -3.805], cities: ['Santander', 'Torrelavega', 'Castro-Urdiales', 'Camargo', 'Piélagos'] },
    'Castellón': { coords: [39.986, -0.037], cities: ['Castellón de la Plana', 'Vila-real', 'Burriana', 'Vinaròs', 'Onda'] },
    'Ceuta': { coords: [35.889, -5.317], cities: ['Ceuta'] },
    'Ciudad Real': { coords: [38.986, -3.927], cities: ['Ciudad Real', 'Puertollano', 'Tomelloso', 'Alcázar de San Juan', 'Valdepeñas'] },
    'Córdoba': { coords: [37.889, -4.779], cities: ['Córdoba', 'Lucena', 'Puente Genil', 'Montilla', 'Priego de Córdoba'] },
    'Cuenca': { coords: [40.070, -2.137], cities: ['Cuenca', 'Tarancón', 'Quintanar del Rey', 'San Clemente'] },
    'Girona': { coords: [41.983, 2.824], cities: ['Girona', 'Figueres', 'Blanes', 'Lloret de Mar', 'Olot', 'Salt'] },
    'Granada': { coords: [37.177, -3.598], cities: ['Granada', 'Motril', 'Almuñécar', 'Armilla', 'Baza', 'Loja'] },
    'Guadalajara': { coords: [40.633, -3.167], cities: ['Guadalajara', 'Azuqueca de Henares', 'Alovera', 'Cabanillas del Campo'] },
    'Guipúzcoa': { coords: [43.318, -1.981], cities: ['San Sebastián', 'Irún', 'Errenteria', 'Eibar', 'Zarautz'] },
    'Huelva': { coords: [37.261, -6.944], cities: ['Huelva', 'Lepe', 'Almonte', 'Ayamonte', 'Isla Cristina'] },
    'Huesca': { coords: [42.140, -0.408], cities: ['Huesca', 'Monzón', 'Barbastro', 'Jaca', 'Fraga'] },
    'Jaén': { coords: [37.766, -3.791], cities: ['Jaén', 'Linares', 'Andújar', 'Úbeda', 'Martos'] },
    'La Rioja': { coords: [42.465, -2.449], cities: ['Logroño', 'Calahorra', 'Arnedo', 'Haro', 'Lardero'] },
    'Las Palmas': { coords: [28.124, -15.430], cities: ['Las Palmas de Gran Canaria', 'Telde', 'Santa Lucía de Tirajana', 'Arrecife', 'San Bartolomé de Tirajana'] },
    'León': { coords: [42.599, -5.567], cities: ['León', 'Ponferrada', 'San Andrés del Rabanedo', 'Astorga'] },
    'Lleida': { coords: [41.617, 0.620], cities: ['Lleida', 'Balaguer', 'Tàrrega', 'Mollerussa', 'La Seu d’Urgell'] },
    'Lugo': { coords: [43.012, -7.556], cities: ['Lugo', 'Monforte de Lemos', 'Viveiro', 'Vilalba'] },
    'Madrid': { coords: [40.417, -3.704], cities: ['Madrid', 'Móstoles', 'Alcalá de Henares', 'Fuenlabrada', 'Leganés', 'Getafe', 'Alcorcón', 'Torrejón de Ardoz', 'Parla', 'Alcobendas', 'Las Rozas de Madrid', 'San Sebastián de los Reyes', 'Pozuelo de Alarcón', 'Coslada'] },
    'Málaga': { coords: [36.721, -4.421], cities: ['Málaga', 'Marbella', 'Vélez-Málaga', 'Mijas', 'Fuengirola', 'Torremolinos', 'Estepona', 'Benalmádena'] },
    'Melilla': { coords: [35.292, -2.938], cities: ['Melilla'] },
    'Murcia': { coords: [37.984, -1.129], cities: ['Murcia', 'Cartagena', 'Lorca', 'Molina de Segura', 'Alcantarilla', 'Yecla'] },
    'Navarra': { coords: [42.813, -1.646], cities: ['Pamplona', 'Tudela', 'Barañáin', 'Burlada', 'Estella'] },
    'Ourense': { coords: [42.336, -7.864], cities: ['Ourense', 'Verín', 'O Barco de Valdeorras', 'O Carballiño'] },
    'Palencia': { coords: [42.009, -4.529], cities: ['Palencia', 'Aguilar de Campoo', 'Guardo', 'Venta de Baños'] },
    'Pontevedra': { coords: [42.431, -8.644], cities: ['Vigo', 'Pontevedra', 'Vilagarcía de Arousa', 'Redondela', 'Marín'] },
    'Salamanca': { coords: [40.970, -5.664], cities: ['Salamanca', 'Béjar', 'Ciudad Rodrigo', 'Santa Marta de Tormes'] },
    'Santa Cruz de Tenerife': { coords: [28.469, -16.255], cities: ['Santa Cruz de Tenerife', 'San Cristóbal de La Laguna', 'Arona', 'Adeje', 'Los Realejos', 'La Orotava'] },
    'Segovia': { coords: [40.943, -4.109], cities: ['Segovia', 'Cuéllar', 'El Espinar', 'San Ildefonso'] },
    'Sevilla': { coords: [37.389, -5.984], cities: ['Sevilla', 'Dos Hermanas', 'Alcalá de Guadaíra', 'Utrera', 'Mairena del Aljarafe', 'Écija'] },
    'Soria': { coords: [41.764, -2.465], cities: ['Soria', 'Almazán', 'El Burgo de Osma', 'Ólvega'] },
    'Tarragona': { coords: [41.119, 1.245], cities: ['Tarragona', 'Reus', 'El Vendrell', 'Cambrils', 'Salou', 'Tortosa'] },
    'Teruel': { coords: [40.344, -1.107], cities: ['Teruel', 'Alcañiz', 'Andorra', 'Calamocha'] },
    'Toledo': { coords: [39.863, -4.028], cities: ['Toledo', 'Talavera de la Reina', 'Illescas', 'Seseña', 'Torrijos'] },
    'Valencia': { coords: [39.470, -0.376], cities: ['Valencia', 'Gandía', 'Torrent', 'Paterna', 'Sagunto', 'Alzira', 'Mislata'] },
    'Valladolid': { coords: [41.652, -4.724], cities: ['Valladolid', 'Medina del Campo', 'Laguna de Duero', 'Arroyo de la Encomienda'] },
    'Vizcaya': { coords: [43.263, -2.935], cities: ['Bilbao', 'Barakaldo', 'Getxo', 'Portugalete', 'Santurtzi', 'Basauri'] },
    'Zamora': { coords: [41.503, -5.744], cities: ['Zamora', 'Benavente', 'Toro', 'Morales del Vino'] },
    'Zaragoza': { coords: [41.649, -0.888], cities: ['Zaragoza', 'Calatayud', 'Utebo', 'Ejea de los Caballeros', 'Tarazona'] },
  },
};
