/* United States · states (50) + District of Columbia → major cities
 * Used by the two-level location picker in Personal details. Same shape as the other countries
 * (MUNEA_REGIONS registry). The second level lists each state's largest cities, not every
 * incorporated place — anything else is typed in under "Other", so we never ship
 * unverified region data (Munea honesty rule).
 * coords = state capital or largest city, used for weather and air quality (Open-Meteo, worldwide).
 * Added 2026-07-31 after Edward chose per-country administrative lists. */
window.MUNEA_REGIONS = window.MUNEA_REGIONS || {};
window.MUNEA_REGIONS.US = {
  countryCode: 'US',
  tier1Key: 'profile.regionTier1State',
  tier2Key: 'profile.regionTier2City',
  otherKey: 'profile.regionOther',
  regions: {
    'Alabama': { coords: [32.377, -86.301], cities: ['Birmingham', 'Montgomery', 'Huntsville', 'Mobile', 'Tuscaloosa'] },
    'Alaska': { coords: [61.218, -149.900], cities: ['Anchorage', 'Fairbanks', 'Juneau', 'Wasilla'] },
    'Arizona': { coords: [33.448, -112.074], cities: ['Phoenix', 'Tucson', 'Mesa', 'Chandler', 'Scottsdale', 'Glendale'] },
    'Arkansas': { coords: [34.746, -92.290], cities: ['Little Rock', 'Fayetteville', 'Fort Smith', 'Springdale'] },
    'California': { coords: [38.582, -121.494], cities: ['Los Angeles', 'San Diego', 'San Jose', 'San Francisco', 'Fresno', 'Sacramento', 'Long Beach', 'Oakland', 'Bakersfield', 'Anaheim', 'Santa Ana', 'Irvine', 'Riverside', 'Stockton'] },
    'Colorado': { coords: [39.739, -104.990], cities: ['Denver', 'Colorado Springs', 'Aurora', 'Fort Collins', 'Lakewood', 'Boulder'] },
    'Connecticut': { coords: [41.764, -72.682], cities: ['Bridgeport', 'New Haven', 'Stamford', 'Hartford', 'Waterbury'] },
    'Delaware': { coords: [39.158, -75.524], cities: ['Wilmington', 'Dover', 'Newark', 'Middletown'] },
    'District of Columbia': { coords: [38.907, -77.037], cities: ['Washington'] },
    'Florida': { coords: [30.438, -84.281], cities: ['Jacksonville', 'Miami', 'Tampa', 'Orlando', 'St. Petersburg', 'Hialeah', 'Tallahassee', 'Fort Lauderdale', 'Cape Coral', 'Naples'] },
    'Georgia': { coords: [33.749, -84.388], cities: ['Atlanta', 'Augusta', 'Columbus', 'Savannah', 'Athens', 'Macon'] },
    'Hawaii': { coords: [21.307, -157.858], cities: ['Honolulu', 'Hilo', 'Kailua', 'Kapolei'] },
    'Idaho': { coords: [43.615, -116.202], cities: ['Boise', 'Meridian', 'Nampa', 'Idaho Falls', 'Pocatello'] },
    'Illinois': { coords: [39.798, -89.644], cities: ['Chicago', 'Aurora', 'Naperville', 'Joliet', 'Rockford', 'Springfield', 'Peoria'] },
    'Indiana': { coords: [39.768, -86.158], cities: ['Indianapolis', 'Fort Wayne', 'Evansville', 'South Bend', 'Carmel', 'Bloomington'] },
    'Iowa': { coords: [41.591, -93.604], cities: ['Des Moines', 'Cedar Rapids', 'Davenport', 'Iowa City', 'Sioux City'] },
    'Kansas': { coords: [39.048, -95.678], cities: ['Wichita', 'Overland Park', 'Kansas City', 'Topeka', 'Olathe'] },
    'Kentucky': { coords: [38.204, -84.874], cities: ['Louisville', 'Lexington', 'Bowling Green', 'Owensboro', 'Covington'] },
    'Louisiana': { coords: [30.451, -91.187], cities: ['New Orleans', 'Baton Rouge', 'Shreveport', 'Lafayette', 'Lake Charles'] },
    'Maine': { coords: [44.307, -69.782], cities: ['Portland', 'Lewiston', 'Bangor', 'Augusta'] },
    'Maryland': { coords: [38.979, -76.492], cities: ['Baltimore', 'Columbia', 'Silver Spring', 'Frederick', 'Rockville', 'Annapolis'] },
    'Massachusetts': { coords: [42.360, -71.058], cities: ['Boston', 'Worcester', 'Springfield', 'Cambridge', 'Lowell', 'Quincy'] },
    'Michigan': { coords: [42.734, -84.556], cities: ['Detroit', 'Grand Rapids', 'Warren', 'Ann Arbor', 'Lansing', 'Sterling Heights'] },
    'Minnesota': { coords: [44.954, -93.090], cities: ['Minneapolis', 'St. Paul', 'Rochester', 'Duluth', 'Bloomington'] },
    'Mississippi': { coords: [32.299, -90.185], cities: ['Jackson', 'Gulfport', 'Southaven', 'Hattiesburg', 'Biloxi'] },
    'Missouri': { coords: [38.579, -92.173], cities: ['Kansas City', 'St. Louis', 'Springfield', 'Columbia', 'Independence'] },
    'Montana': { coords: [46.586, -112.018], cities: ['Billings', 'Missoula', 'Great Falls', 'Bozeman', 'Helena'] },
    'Nebraska': { coords: [40.808, -96.700], cities: ['Omaha', 'Lincoln', 'Bellevue', 'Grand Island'] },
    'Nevada': { coords: [39.164, -119.767], cities: ['Las Vegas', 'Henderson', 'Reno', 'North Las Vegas', 'Sparks'] },
    'New Hampshire': { coords: [43.207, -71.538], cities: ['Manchester', 'Nashua', 'Concord', 'Dover'] },
    'New Jersey': { coords: [40.220, -74.770], cities: ['Newark', 'Jersey City', 'Paterson', 'Elizabeth', 'Edison', 'Trenton'] },
    'New Mexico': { coords: [35.687, -105.938], cities: ['Albuquerque', 'Las Cruces', 'Rio Rancho', 'Santa Fe'] },
    'New York': { coords: [42.652, -73.757], cities: ['New York City', 'Buffalo', 'Rochester', 'Yonkers', 'Syracuse', 'Albany', 'New Rochelle'] },
    'North Carolina': { coords: [35.780, -78.639], cities: ['Charlotte', 'Raleigh', 'Greensboro', 'Durham', 'Winston-Salem', 'Fayetteville'] },
    'North Dakota': { coords: [46.809, -100.784], cities: ['Fargo', 'Bismarck', 'Grand Forks', 'Minot'] },
    'Ohio': { coords: [39.961, -82.999], cities: ['Columbus', 'Cleveland', 'Cincinnati', 'Toledo', 'Akron', 'Dayton'] },
    'Oklahoma': { coords: [35.468, -97.516], cities: ['Oklahoma City', 'Tulsa', 'Norman', 'Broken Arrow', 'Edmond'] },
    'Oregon': { coords: [44.938, -123.030], cities: ['Portland', 'Salem', 'Eugene', 'Gresham', 'Beaverton', 'Bend'] },
    'Pennsylvania': { coords: [40.264, -76.884], cities: ['Philadelphia', 'Pittsburgh', 'Allentown', 'Harrisburg', 'Erie', 'Reading'] },
    'Rhode Island': { coords: [41.824, -71.413], cities: ['Providence', 'Warwick', 'Cranston', 'Pawtucket'] },
    'South Carolina': { coords: [34.001, -81.035], cities: ['Charleston', 'Columbia', 'North Charleston', 'Greenville', 'Myrtle Beach'] },
    'South Dakota': { coords: [44.368, -100.351], cities: ['Sioux Falls', 'Rapid City', 'Aberdeen', 'Pierre'] },
    'Tennessee': { coords: [36.163, -86.781], cities: ['Nashville', 'Memphis', 'Knoxville', 'Chattanooga', 'Clarksville'] },
    'Texas': { coords: [30.267, -97.743], cities: ['Houston', 'San Antonio', 'Dallas', 'Austin', 'Fort Worth', 'El Paso', 'Arlington', 'Corpus Christi', 'Plano', 'Laredo'] },
    'Utah': { coords: [40.761, -111.891], cities: ['Salt Lake City', 'West Valley City', 'Provo', 'Ogden', 'St. George'] },
    'Vermont': { coords: [44.260, -72.575], cities: ['Burlington', 'South Burlington', 'Rutland', 'Montpelier'] },
    'Virginia': { coords: [37.541, -77.436], cities: ['Virginia Beach', 'Richmond', 'Norfolk', 'Chesapeake', 'Arlington', 'Alexandria'] },
    'Washington': { coords: [47.038, -122.901], cities: ['Seattle', 'Spokane', 'Tacoma', 'Vancouver', 'Bellevue', 'Everett', 'Olympia'] },
    'West Virginia': { coords: [38.337, -81.612], cities: ['Charleston', 'Huntington', 'Morgantown', 'Parkersburg'] },
    'Wisconsin': { coords: [43.074, -89.384], cities: ['Milwaukee', 'Madison', 'Green Bay', 'Kenosha', 'Racine', 'Appleton'] },
    'Wyoming': { coords: [41.140, -104.820], cities: ['Cheyenne', 'Casper', 'Laramie', 'Gillette'] },
  },
};
