"""五國「地名 → 一級行政區＋經緯度」對照（自動產生、勿手改）。

正本＝web/src/tw-districts.js 與 web/src/regions/*.js。
長輩只會講地名，這張表把地名對回查得到天氣的地方；跨行政區同名的不收（猜錯＝報錯城市）。
產生方式：node scripts/gen-region-index.js
"""

REGIONS = {
    "ES": {
        "tier1": {
            "A Coruña": (43.371, -8.396),
            "Albacete": (38.994, -1.858),
            "Alicante": (38.345, -0.481),
            "Almería": (36.834, -2.464),
            "Asturias": (43.362, -5.849),
            "Badajoz": (38.879, -6.97),
            "Baleares": (39.57, 2.65),
            "Barcelona": (41.385, 2.173),
            "Burgos": (42.344, -3.697),
            "Cantabria": (43.463, -3.805),
            "Castellón": (39.986, -0.037),
            "Ceuta": (35.889, -5.317),
            "Ciudad Real": (38.986, -3.927),
            "Cuenca": (40.07, -2.137),
            "Cáceres": (39.476, -6.372),
            "Cádiz": (36.527, -6.289),
            "Córdoba": (37.889, -4.779),
            "Girona": (41.983, 2.824),
            "Granada": (37.177, -3.598),
            "Guadalajara": (40.633, -3.167),
            "Guipúzcoa": (43.318, -1.981),
            "Huelva": (37.261, -6.944),
            "Huesca": (42.14, -0.408),
            "Jaén": (37.766, -3.791),
            "La Rioja": (42.465, -2.449),
            "Las Palmas": (28.124, -15.43),
            "León": (42.599, -5.567),
            "Lleida": (41.617, 0.62),
            "Lugo": (43.012, -7.556),
            "Madrid": (40.417, -3.704),
            "Melilla": (35.292, -2.938),
            "Murcia": (37.984, -1.129),
            "Málaga": (36.721, -4.421),
            "Navarra": (42.813, -1.646),
            "Ourense": (42.336, -7.864),
            "Palencia": (42.009, -4.529),
            "Pontevedra": (42.431, -8.644),
            "Salamanca": (40.97, -5.664),
            "Santa Cruz de Tenerife": (28.469, -16.255),
            "Segovia": (40.943, -4.109),
            "Sevilla": (37.389, -5.984),
            "Soria": (41.764, -2.465),
            "Tarragona": (41.119, 1.245),
            "Teruel": (40.344, -1.107),
            "Toledo": (39.863, -4.028),
            "Valencia": (39.47, -0.376),
            "Valladolid": (41.652, -4.724),
            "Vizcaya": (43.263, -2.935),
            "Zamora": (41.503, -5.744),
            "Zaragoza": (41.649, -0.888),
            "Álava": (42.847, -2.673),
            "Ávila": (40.657, -4.7),
        },
        "tier2_to_tier1": {
            "A Coruña": "A Coruña",
            "Adeje": "Santa Cruz de Tenerife",
            "Adra": "Almería",
            "Aguilar de Campoo": "Palencia",
            "Albacete": "Albacete",
            "Alcalá de Guadaíra": "Sevilla",
            "Alcalá de Henares": "Madrid",
            "Alcantarilla": "Murcia",
            "Alcañiz": "Teruel",
            "Alcobendas": "Madrid",
            "Alcorcón": "Madrid",
            "Alcoy": "Alicante",
            "Alcázar de San Juan": "Ciudad Real",
            "Algeciras": "Cádiz",
            "Alicante": "Alicante",
            "Almansa": "Albacete",
            "Almazán": "Soria",
            "Almendralejo": "Badajoz",
            "Almería": "Almería",
            "Almonte": "Huelva",
            "Almuñécar": "Granada",
            "Alovera": "Guadalajara",
            "Alzira": "Valencia",
            "Amurrio": "Álava",
            "Andorra": "Teruel",
            "Andújar": "Jaén",
            "Aranda de Duero": "Burgos",
            "Arenas de San Pedro": "Ávila",
            "Armilla": "Granada",
            "Arnedo": "La Rioja",
            "Arona": "Santa Cruz de Tenerife",
            "Arrecife": "Las Palmas",
            "Arroyo de la Encomienda": "Valladolid",
            "Arévalo": "Ávila",
            "Astorga": "León",
            "Avilés": "Asturias",
            "Ayamonte": "Huelva",
            "Azuqueca de Henares": "Guadalajara",
            "Badajoz": "Badajoz",
            "Badalona": "Barcelona",
            "Balaguer": "Lleida",
            "Barakaldo": "Vizcaya",
            "Barañáin": "Navarra",
            "Barbastro": "Huesca",
            "Barcelona": "Barcelona",
            "Basauri": "Vizcaya",
            "Baza": "Granada",
            "Benalmádena": "Málaga",
            "Benavente": "Zamora",
            "Benidorm": "Alicante",
            "Bilbao": "Vizcaya",
            "Blanes": "Girona",
            "Briviesca": "Burgos",
            "Burgos": "Burgos",
            "Burlada": "Navarra",
            "Burriana": "Castellón",
            "Béjar": "Salamanca",
            "Cabanillas del Campo": "Guadalajara",
            "Calahorra": "La Rioja",
            "Calamocha": "Teruel",
            "Calatayud": "Zaragoza",
            "Calvià": "Baleares",
            "Camargo": "Cantabria",
            "Cambrils": "Tarragona",
            "Cartagena": "Murcia",
            "Castellón de la Plana": "Castellón",
            "Castro-Urdiales": "Cantabria",
            "Ceuta": "Ceuta",
            "Chiclana de la Frontera": "Cádiz",
            "Ciudad Real": "Ciudad Real",
            "Ciudad Rodrigo": "Salamanca",
            "Coria": "Cáceres",
            "Cornellà de Llobregat": "Barcelona",
            "Coslada": "Madrid",
            "Cuenca": "Cuenca",
            "Cuéllar": "Segovia",
            "Cáceres": "Cáceres",
            "Cádiz": "Cádiz",
            "Córdoba": "Córdoba",
            "Don Benito": "Badajoz",
            "Dos Hermanas": "Sevilla",
            "Eibar": "Guipúzcoa",
            "Ejea de los Caballeros": "Zaragoza",
            "El Burgo de Osma": "Soria",
            "El Ejido": "Almería",
            "El Espinar": "Segovia",
            "El Puerto de Santa María": "Cádiz",
            "El Vendrell": "Tarragona",
            "Elche": "Alicante",
            "Elda": "Alicante",
            "Errenteria": "Guipúzcoa",
            "Estella": "Navarra",
            "Estepona": "Málaga",
            "Ferrol": "A Coruña",
            "Figueres": "Girona",
            "Fraga": "Huesca",
            "Fuengirola": "Málaga",
            "Fuenlabrada": "Madrid",
            "Gandía": "Valencia",
            "Getafe": "Madrid",
            "Getxo": "Vizcaya",
            "Gijón": "Asturias",
            "Girona": "Girona",
            "Granada": "Granada",
            "Guadalajara": "Guadalajara",
            "Guardo": "Palencia",
            "Haro": "La Rioja",
            "Hellín": "Albacete",
            "Huelva": "Huelva",
            "Huesca": "Huesca",
            "Ibiza": "Baleares",
            "Illescas": "Toledo",
            "Irún": "Guipúzcoa",
            "Isla Cristina": "Huelva",
            "Jaca": "Huesca",
            "Jaén": "Jaén",
            "Jerez de la Frontera": "Cádiz",
            "L'Hospitalet de Llobregat": "Barcelona",
            "La Línea de la Concepción": "Cádiz",
            "La Orotava": "Santa Cruz de Tenerife",
            "La Roda": "Albacete",
            "La Seu d’Urgell": "Lleida",
            "Laguna de Duero": "Valladolid",
            "Langreo": "Asturias",
            "Lardero": "La Rioja",
            "Las Navas del Marqués": "Ávila",
            "Las Palmas de Gran Canaria": "Las Palmas",
            "Las Rozas de Madrid": "Madrid",
            "Leganés": "Madrid",
            "Lepe": "Huelva",
            "León": "León",
            "Linares": "Jaén",
            "Lleida": "Lleida",
            "Llodio": "Álava",
            "Lloret de Mar": "Girona",
            "Llucmajor": "Baleares",
            "Logroño": "La Rioja",
            "Loja": "Granada",
            "Lorca": "Murcia",
            "Los Realejos": "Santa Cruz de Tenerife",
            "Lucena": "Córdoba",
            "Lugo": "Lugo",
            "Madrid": "Madrid",
            "Mahón": "Baleares",
            "Mairena del Aljarafe": "Sevilla",
            "Manacor": "Baleares",
            "Manresa": "Barcelona",
            "Marbella": "Málaga",
            "Marratxí": "Baleares",
            "Martos": "Jaén",
            "Marín": "Pontevedra",
            "Mataró": "Barcelona",
            "Medina del Campo": "Valladolid",
            "Melilla": "Melilla",
            "Mieres": "Asturias",
            "Mijas": "Málaga",
            "Miranda de Ebro": "Burgos",
            "Mislata": "Valencia",
            "Molina de Segura": "Murcia",
            "Mollerussa": "Lleida",
            "Monforte de Lemos": "Lugo",
            "Montilla": "Córdoba",
            "Monzón": "Huesca",
            "Morales del Vino": "Zamora",
            "Motril": "Granada",
            "Murcia": "Murcia",
            "Málaga": "Málaga",
            "Mérida": "Badajoz",
            "Móstoles": "Madrid",
            "Narón": "A Coruña",
            "Navalmoral de la Mata": "Cáceres",
            "Níjar": "Almería",
            "O Barco de Valdeorras": "Ourense",
            "O Carballiño": "Ourense",
            "Oleiros": "A Coruña",
            "Olot": "Girona",
            "Onda": "Castellón",
            "Orihuela": "Alicante",
            "Ourense": "Ourense",
            "Oviedo": "Asturias",
            "Palencia": "Palencia",
            "Palma": "Baleares",
            "Pamplona": "Navarra",
            "Parla": "Madrid",
            "Paterna": "Valencia",
            "Piélagos": "Cantabria",
            "Plasencia": "Cáceres",
            "Ponferrada": "León",
            "Pontevedra": "Pontevedra",
            "Portugalete": "Vizcaya",
            "Pozuelo de Alarcón": "Madrid",
            "Priego de Córdoba": "Córdoba",
            "Puente Genil": "Córdoba",
            "Puertollano": "Ciudad Real",
            "Quintanar del Rey": "Cuenca",
            "Redondela": "Pontevedra",
            "Reus": "Tarragona",
            "Roquetas de Mar": "Almería",
            "Sabadell": "Barcelona",
            "Sagunto": "Valencia",
            "Salamanca": "Salamanca",
            "Salou": "Tarragona",
            "Salt": "Girona",
            "Salvatierra": "Álava",
            "San Andrés del Rabanedo": "León",
            "San Bartolomé de Tirajana": "Las Palmas",
            "San Clemente": "Cuenca",
            "San Cristóbal de La Laguna": "Santa Cruz de Tenerife",
            "San Fernando": "Cádiz",
            "San Ildefonso": "Segovia",
            "San Sebastián": "Guipúzcoa",
            "San Sebastián de los Reyes": "Madrid",
            "Sant Cugat del Vallès": "Barcelona",
            "Santa Coloma de Gramenet": "Barcelona",
            "Santa Cruz de Tenerife": "Santa Cruz de Tenerife",
            "Santa Lucía de Tirajana": "Las Palmas",
            "Santa Marta de Tormes": "Salamanca",
            "Santander": "Cantabria",
            "Santiago de Compostela": "A Coruña",
            "Santurtzi": "Vizcaya",
            "Segovia": "Segovia",
            "Seseña": "Toledo",
            "Sevilla": "Sevilla",
            "Siero": "Asturias",
            "Soria": "Soria",
            "Talavera de la Reina": "Toledo",
            "Tarancón": "Cuenca",
            "Tarazona": "Zaragoza",
            "Tarragona": "Tarragona",
            "Telde": "Las Palmas",
            "Terrassa": "Barcelona",
            "Teruel": "Teruel",
            "Toledo": "Toledo",
            "Tomelloso": "Ciudad Real",
            "Toro": "Zamora",
            "Torrejón de Ardoz": "Madrid",
            "Torrelavega": "Cantabria",
            "Torremolinos": "Málaga",
            "Torrent": "Valencia",
            "Torrevieja": "Alicante",
            "Torrijos": "Toledo",
            "Tortosa": "Tarragona",
            "Trujillo": "Cáceres",
            "Tudela": "Navarra",
            "Tàrrega": "Lleida",
            "Utebo": "Zaragoza",
            "Utrera": "Sevilla",
            "Valdepeñas": "Ciudad Real",
            "Valencia": "Valencia",
            "Valladolid": "Valladolid",
            "Venta de Baños": "Palencia",
            "Verín": "Ourense",
            "Vigo": "Pontevedra",
            "Vila-real": "Castellón",
            "Vilagarcía de Arousa": "Pontevedra",
            "Vilalba": "Lugo",
            "Villanueva de la Serena": "Badajoz",
            "Villarrobledo": "Albacete",
            "Vinaròs": "Castellón",
            "Vitoria-Gasteiz": "Álava",
            "Viveiro": "Lugo",
            "Vélez-Málaga": "Málaga",
            "Yecla": "Murcia",
            "Zamora": "Zamora",
            "Zaragoza": "Zaragoza",
            "Zarautz": "Guipúzcoa",
            "Ávila": "Ávila",
            "Écija": "Sevilla",
            "Ólvega": "Soria",
            "Úbeda": "Jaén",
        },
        "ambiguous": frozenset({}),
    },
    "GB": {
        "tier1": {
            "East Midlands": (52.955, -1.15),
            "East of England": (52.205, 0.121),
            "Greater London": (51.507, -0.128),
            "North East England": (54.978, -1.618),
            "North West England": (53.481, -2.242),
            "Northern Ireland": (54.597, -5.93),
            "Scotland": (55.953, -3.189),
            "South East England": (50.827, -0.153),
            "South West England": (51.455, -2.587),
            "Wales": (51.481, -3.179),
            "West Midlands": (52.486, -1.89),
            "Yorkshire and the Humber": (53.801, -1.549),
        },
        "tier2_to_tier1": {
            "Aberdeen": "Scotland",
            "Barnet": "Greater London",
            "Barry": "Wales",
            "Basingstoke": "South East England",
            "Bath": "South West England",
            "Belfast": "Northern Ireland",
            "Birmingham": "West Midlands",
            "Blackpool": "North West England",
            "Bolton": "North West England",
            "Bournemouth": "South West England",
            "Bradford": "Yorkshire and the Humber",
            "Brighton": "South East England",
            "Bristol": "South West England",
            "Bromley": "Greater London",
            "Cambridge": "East of England",
            "Canterbury": "South East England",
            "Cardiff": "Wales",
            "Chelmsford": "East of England",
            "Chester": "North West England",
            "Chesterfield": "East Midlands",
            "Colchester": "East of England",
            "Coventry": "West Midlands",
            "Craigavon": "Northern Ireland",
            "Croydon": "Greater London",
            "Darlington": "North East England",
            "Derby": "East Midlands",
            "Doncaster": "Yorkshire and the Humber",
            "Dundee": "Scotland",
            "Durham": "North East England",
            "Ealing": "Greater London",
            "Edinburgh": "Scotland",
            "Enfield": "Greater London",
            "Exeter": "South West England",
            "Gateshead": "North East England",
            "Glasgow": "Scotland",
            "Gloucester": "South West England",
            "Hounslow": "Greater London",
            "Huddersfield": "Yorkshire and the Humber",
            "Hull": "Yorkshire and the Humber",
            "Inverness": "Scotland",
            "Ipswich": "East of England",
            "Leeds": "Yorkshire and the Humber",
            "Leicester": "East Midlands",
            "Lincoln": "East Midlands",
            "Lisburn": "Northern Ireland",
            "Liverpool": "North West England",
            "London": "Greater London",
            "Londonderry": "Northern Ireland",
            "Luton": "East of England",
            "Manchester": "North West England",
            "Middlesbrough": "North East England",
            "Milton Keynes": "South East England",
            "Newcastle upon Tyne": "North East England",
            "Newport": "Wales",
            "Newry": "Northern Ireland",
            "Northampton": "East Midlands",
            "Norwich": "East of England",
            "Nottingham": "East Midlands",
            "Oxford": "South East England",
            "Paisley": "Scotland",
            "Perth": "Scotland",
            "Peterborough": "East of England",
            "Plymouth": "South West England",
            "Portsmouth": "South East England",
            "Preston": "North West England",
            "Reading": "South East England",
            "Richmond upon Thames": "Greater London",
            "Sheffield": "Yorkshire and the Humber",
            "Slough": "South East England",
            "Solihull": "West Midlands",
            "Southampton": "South East England",
            "Southend-on-Sea": "East of England",
            "Stirling": "Scotland",
            "Stockport": "North West England",
            "Stoke-on-Trent": "West Midlands",
            "Sunderland": "North East England",
            "Swansea": "Wales",
            "Swindon": "South West England",
            "Telford": "West Midlands",
            "Torquay": "South West England",
            "Wakefield": "Yorkshire and the Humber",
            "Warrington": "North West England",
            "Wolverhampton": "West Midlands",
            "Worcester": "West Midlands",
            "Wrexham": "Wales",
            "York": "Yorkshire and the Humber",
        },
        "ambiguous": frozenset({"Bangor"}),
    },
    "JP": {
        "tier1": {
            "三重県": (34.73, 136.509),
            "京都府": (35.021, 135.756),
            "佐賀県": (33.249, 130.3),
            "兵庫県": (34.691, 135.183),
            "北海道": (43.064, 141.347),
            "千葉県": (35.605, 140.123),
            "和歌山県": (34.226, 135.167),
            "埼玉県": (35.857, 139.649),
            "大分県": (33.238, 131.613),
            "大阪府": (34.686, 135.52),
            "奈良県": (34.685, 135.833),
            "宮城県": (38.269, 140.872),
            "宮崎県": (31.911, 131.424),
            "富山県": (36.695, 137.211),
            "山口県": (34.186, 131.471),
            "山形県": (38.24, 140.364),
            "山梨県": (35.664, 138.568),
            "岐阜県": (35.391, 136.722),
            "岡山県": (34.662, 133.935),
            "岩手県": (39.704, 141.153),
            "島根県": (35.472, 133.051),
            "広島県": (34.396, 132.46),
            "徳島県": (34.066, 134.559),
            "愛媛県": (33.842, 132.766),
            "愛知県": (35.18, 136.907),
            "新潟県": (37.902, 139.023),
            "東京都": (35.69, 139.692),
            "栃木県": (36.566, 139.884),
            "沖縄県": (26.212, 127.681),
            "滋賀県": (35.005, 135.869),
            "熊本県": (32.79, 130.742),
            "石川県": (36.595, 136.626),
            "神奈川県": (35.448, 139.643),
            "福井県": (36.065, 136.222),
            "福岡県": (33.607, 130.418),
            "福島県": (37.75, 140.468),
            "秋田県": (39.719, 140.102),
            "群馬県": (36.391, 139.06),
            "茨城県": (36.342, 140.447),
            "長崎県": (32.745, 129.874),
            "長野県": (36.651, 138.181),
            "青森県": (40.824, 140.74),
            "静岡県": (34.977, 138.383),
            "香川県": (34.34, 134.043),
            "高知県": (33.56, 133.531),
            "鳥取県": (35.504, 134.238),
            "鹿児島県": (31.56, 130.558),
        },
        "tier2_to_tier1": {
            "いわき市": "福島県",
            "うるま市": "沖縄県",
            "さいたま市": "埼玉県",
            "つくば市": "茨城県",
            "ひたちなか市": "茨城県",
            "むつ市": "青森県",
            "一宮市": "愛知県",
            "一関市": "岩手県",
            "七尾市": "石川県",
            "三条市": "新潟県",
            "三豊市": "香川県",
            "三鷹市": "東京都",
            "上田市": "長野県",
            "上越市": "新潟県",
            "下関市": "山口県",
            "世田谷区": "東京都",
            "中央区": "東京都",
            "中津市": "大分県",
            "中野区": "東京都",
            "丸亀市": "香川県",
            "久留米市": "福岡県",
            "亀岡市": "京都府",
            "京都市": "京都府",
            "今治市": "愛媛県",
            "仙台市": "宮城県",
            "伊万里市": "佐賀県",
            "伊勢崎市": "群馬県",
            "伊勢市": "三重県",
            "会津若松市": "福島県",
            "佐世保市": "長崎県",
            "佐久市": "長野県",
            "佐伯市": "大分県",
            "佐賀市": "佐賀県",
            "佐野市": "栃木県",
            "倉吉市": "鳥取県",
            "倉敷市": "岡山県",
            "八代市": "熊本県",
            "八千代市": "千葉県",
            "八戸市": "青森県",
            "八王子市": "東京都",
            "出雲市": "島根県",
            "函館市": "北海道",
            "別府市": "大分県",
            "前橋市": "群馬県",
            "加古川市": "兵庫県",
            "加賀市": "石川県",
            "北上市": "岩手県",
            "北九州市": "福岡県",
            "北区": "東京都",
            "北見市": "北海道",
            "十和田市": "青森県",
            "千代田区": "東京都",
            "千葉市": "千葉県",
            "南アルプス市": "山梨県",
            "南国市": "高知県",
            "南砺市": "富山県",
            "厚木市": "神奈川県",
            "古河市": "茨城県",
            "台東区": "東京都",
            "各務原市": "岐阜県",
            "合志市": "熊本県",
            "吉野川市": "徳島県",
            "名古屋市": "愛知県",
            "名護市": "沖縄県",
            "吹田市": "大阪府",
            "呉市": "広島県",
            "周南市": "山口県",
            "和歌山市": "和歌山県",
            "品川区": "東京都",
            "唐津市": "佐賀県",
            "四万十市": "高知県",
            "四日市市": "三重県",
            "土佐市": "高知県",
            "土浦市": "茨城県",
            "坂井市": "福井県",
            "坂出市": "香川県",
            "堺市": "大阪府",
            "境港市": "鳥取県",
            "墨田区": "東京都",
            "多治見市": "岐阜県",
            "大仙市": "秋田県",
            "大分市": "大分県",
            "大和郡山市": "奈良県",
            "大垣市": "岐阜県",
            "大崎市": "宮城県",
            "大村市": "長崎県",
            "大津市": "滋賀県",
            "大牟田市": "福岡県",
            "大田区": "東京都",
            "大田市": "島根県",
            "大阪市": "大阪府",
            "大館市": "秋田県",
            "天理市": "奈良県",
            "天童市": "山形県",
            "天草市": "熊本県",
            "太田市": "群馬県",
            "奈良市": "奈良県",
            "奥州市": "岩手県",
            "姫路市": "兵庫県",
            "姶良市": "鹿児島県",
            "宇和島市": "愛媛県",
            "宇治市": "京都府",
            "宇部市": "山口県",
            "宇都宮市": "栃木県",
            "安城市": "愛知県",
            "安曇野市": "長野県",
            "宜野湾市": "沖縄県",
            "宝塚市": "兵庫県",
            "室蘭市": "北海道",
            "宮崎市": "宮崎県",
            "富士吉田市": "山梨県",
            "富士市": "静岡県",
            "富山市": "富山県",
            "射水市": "富山県",
            "小山市": "栃木県",
            "小松市": "石川県",
            "小樽市": "北海道",
            "尼崎市": "兵庫県",
            "尾道市": "広島県",
            "山口市": "山口県",
            "山形市": "山形県",
            "岐阜市": "岐阜県",
            "岡山市": "岡山県",
            "岡崎市": "愛知県",
            "岩国市": "山口県",
            "島原市": "長崎県",
            "川口市": "埼玉県",
            "川崎市": "神奈川県",
            "川越市": "埼玉県",
            "市原市": "千葉県",
            "市川市": "千葉県",
            "帯広市": "北海道",
            "平塚市": "神奈川県",
            "広島市": "広島県",
            "府中市": "東京都",
            "延岡市": "宮崎県",
            "廿日市市": "広島県",
            "弘前市": "青森県",
            "彦根市": "滋賀県",
            "徳島市": "徳島県",
            "所沢市": "埼玉県",
            "敦賀市": "福井県",
            "文京区": "東京都",
            "新宿区": "東京都",
            "新居浜市": "愛媛県",
            "新潟市": "新潟県",
            "日南市": "宮崎県",
            "日向市": "宮崎県",
            "日田市": "大分県",
            "日立市": "茨城県",
            "旭川市": "北海道",
            "明石市": "兵庫県",
            "春日井市": "愛知県",
            "春日市": "福岡県",
            "春日部市": "埼玉県",
            "札幌市": "北海道",
            "杉並区": "東京都",
            "東大阪市": "大阪府",
            "東広島市": "広島県",
            "東近江市": "滋賀県",
            "松山市": "愛媛県",
            "松戸市": "千葉県",
            "松本市": "長野県",
            "松江市": "島根県",
            "松阪市": "三重県",
            "板橋区": "東京都",
            "枚方市": "大阪府",
            "柏崎市": "新潟県",
            "柏市": "千葉県",
            "栃木市": "栃木県",
            "栗原市": "宮城県",
            "桐生市": "群馬県",
            "桑名市": "三重県",
            "横手市": "秋田県",
            "横浜市": "神奈川県",
            "横須賀市": "神奈川県",
            "橋本市": "和歌山県",
            "橿原市": "奈良県",
            "武蔵野市": "東京都",
            "武雄市": "佐賀県",
            "水戸市": "茨城県",
            "氷見市": "富山県",
            "江別市": "北海道",
            "江戸川区": "東京都",
            "江東区": "東京都",
            "沖縄市": "沖縄県",
            "沼津市": "静岡県",
            "津山市": "岡山県",
            "津市": "三重県",
            "浜松市": "静岡県",
            "浜田市": "島根県",
            "浦添市": "沖縄県",
            "海南市": "和歌山県",
            "渋谷区": "東京都",
            "港区": "東京都",
            "熊本市": "熊本県",
            "玉名市": "熊本県",
            "玉野市": "岡山県",
            "生駒市": "奈良県",
            "田辺市": "和歌山県",
            "由利本荘市": "秋田県",
            "甲府市": "山梨県",
            "甲斐市": "山梨県",
            "町田市": "東京都",
            "登米市": "宮城県",
            "白山市": "石川県",
            "益田市": "島根県",
            "盛岡市": "岩手県",
            "目黒区": "東京都",
            "相模原市": "神奈川県",
            "石巻市": "宮城県",
            "磐田市": "静岡県",
            "神戸市": "兵庫県",
            "福井市": "福井県",
            "福山市": "広島県",
            "福岡市": "福岡県",
            "福島市": "福島県",
            "秋田市": "秋田県",
            "笛吹市": "山梨県",
            "米子市": "鳥取県",
            "米沢市": "山形県",
            "紀の川市": "和歌山県",
            "総社市": "岡山県",
            "練馬区": "東京都",
            "舞鶴市": "京都府",
            "船橋市": "千葉県",
            "花巻市": "岩手県",
            "苫小牧市": "北海道",
            "茅ヶ崎市": "神奈川県",
            "茨木市": "大阪府",
            "草加市": "埼玉県",
            "草津市": "滋賀県",
            "荒川区": "東京都",
            "葛飾区": "東京都",
            "薩摩川内市": "鹿児島県",
            "藤枝市": "静岡県",
            "藤沢市": "神奈川県",
            "西宮市": "兵庫県",
            "西条市": "愛媛県",
            "西東京市": "東京都",
            "観音寺市": "香川県",
            "調布市": "東京都",
            "諫早市": "長崎県",
            "豊中市": "大阪府",
            "豊島区": "東京都",
            "豊橋市": "愛知県",
            "豊田市": "愛知県",
            "越前市": "福井県",
            "越谷市": "埼玉県",
            "足利市": "栃木県",
            "足立区": "東京都",
            "那覇市": "沖縄県",
            "郡山市": "福島県",
            "都城市": "宮崎県",
            "酒田市": "山形県",
            "金沢市": "石川県",
            "釧路市": "北海道",
            "鈴鹿市": "三重県",
            "長岡京市": "京都府",
            "長岡市": "新潟県",
            "長崎市": "長崎県",
            "長浜市": "滋賀県",
            "長野市": "長野県",
            "阿南市": "徳島県",
            "霧島市": "鹿児島県",
            "青森市": "青森県",
            "静岡市": "静岡県",
            "須賀川市": "福島県",
            "飯塚市": "福岡県",
            "飯田市": "長野県",
            "香南市": "高知県",
            "高山市": "岐阜県",
            "高岡市": "富山県",
            "高崎市": "群馬県",
            "高松市": "香川県",
            "高槻市": "大阪府",
            "高知市": "高知県",
            "鯖江市": "福井県",
            "鳥取市": "鳥取県",
            "鳥栖市": "佐賀県",
            "鳴門市": "徳島県",
            "鶴岡市": "山形県",
            "鹿児島市": "鹿児島県",
            "鹿屋市": "鹿児島県",
        },
        "ambiguous": frozenset({}),
    },
    "TW": {
        "tier1": {
            "南投縣": (23.961, 120.972),
            "台中市": (24.148, 120.674),
            "台北市": (25.033, 121.565),
            "台南市": (22.999, 120.227),
            "台東縣": (22.758, 121.144),
            "嘉義市": (23.48, 120.449),
            "嘉義縣": (23.452, 120.256),
            "基隆市": (25.128, 121.742),
            "宜蘭縣": (24.702, 121.738),
            "屏東縣": (22.552, 120.549),
            "彰化縣": (24.052, 120.516),
            "新北市": (25.017, 121.463),
            "新竹市": (24.804, 120.971),
            "新竹縣": (24.839, 121.008),
            "桃園市": (24.994, 121.301),
            "澎湖縣": (23.566, 119.579),
            "花蓮縣": (23.977, 121.604),
            "苗栗縣": (24.56, 120.821),
            "連江縣": (26.16, 119.951),
            "金門縣": (24.433, 118.317),
            "雲林縣": (23.709, 120.431),
            "高雄市": (22.627, 120.301),
        },
        "tier2_to_tier1": {
            "七堵區": "基隆市",
            "七美鄉": "澎湖縣",
            "七股區": "台南市",
            "三地門鄉": "屏東縣",
            "三峽區": "新北市",
            "三星鄉": "宜蘭縣",
            "三民區": "高雄市",
            "三灣鄉": "苗栗縣",
            "三義鄉": "苗栗縣",
            "三芝區": "新北市",
            "三重區": "新北市",
            "下營區": "台南市",
            "中區": "台中市",
            "中和區": "新北市",
            "中埔鄉": "嘉義縣",
            "中壢區": "桃園市",
            "中寮鄉": "南投縣",
            "中西區": "台南市",
            "九如鄉": "屏東縣",
            "二崙鄉": "雲林縣",
            "二林鎮": "彰化縣",
            "二水鄉": "彰化縣",
            "五峰鄉": "新竹縣",
            "五結鄉": "宜蘭縣",
            "五股區": "新北市",
            "仁德區": "台南市",
            "仁愛區": "基隆市",
            "仁愛鄉": "南投縣",
            "仁武區": "高雄市",
            "伸港鄉": "彰化縣",
            "佳冬鄉": "屏東縣",
            "佳里區": "台南市",
            "來義鄉": "屏東縣",
            "信義鄉": "南投縣",
            "元長鄉": "雲林縣",
            "光復鄉": "花蓮縣",
            "內埔鄉": "屏東縣",
            "內湖區": "台北市",
            "內門區": "高雄市",
            "八德區": "桃園市",
            "八里區": "新北市",
            "公館鄉": "苗栗縣",
            "六甲區": "台南市",
            "六腳鄉": "嘉義縣",
            "六龜區": "高雄市",
            "冬山鄉": "宜蘭縣",
            "前金區": "高雄市",
            "前鎮區": "高雄市",
            "北埔鄉": "新竹縣",
            "北屯區": "台中市",
            "北投區": "台北市",
            "北斗鎮": "彰化縣",
            "北港鎮": "雲林縣",
            "北竿鄉": "連江縣",
            "北門區": "台南市",
            "卑南鄉": "台東縣",
            "卓溪鄉": "花蓮縣",
            "卓蘭鎮": "苗栗縣",
            "南化區": "台南市",
            "南屯區": "台中市",
            "南州鄉": "屏東縣",
            "南庄鄉": "苗栗縣",
            "南投市": "南投縣",
            "南港區": "台北市",
            "南澳鄉": "宜蘭縣",
            "南竿鄉": "連江縣",
            "口湖鄉": "雲林縣",
            "古坑鄉": "雲林縣",
            "台東市": "台東縣",
            "台西鄉": "雲林縣",
            "吉安鄉": "花蓮縣",
            "名間鄉": "南投縣",
            "后里區": "台中市",
            "和平區": "台中市",
            "和美鎮": "彰化縣",
            "員山鄉": "宜蘭縣",
            "員林市": "彰化縣",
            "善化區": "台南市",
            "四湖鄉": "雲林縣",
            "國姓鄉": "南投縣",
            "土城區": "新北市",
            "土庫鎮": "雲林縣",
            "坪林區": "新北市",
            "埔心鄉": "彰化縣",
            "埔里鎮": "南投縣",
            "埔鹽鄉": "彰化縣",
            "埤頭鄉": "彰化縣",
            "士林區": "台北市",
            "壯圍鄉": "宜蘭縣",
            "壽豐鄉": "花蓮縣",
            "外埔區": "台中市",
            "大內區": "台南市",
            "大同區": "台北市",
            "大同鄉": "宜蘭縣",
            "大園區": "桃園市",
            "大城鄉": "彰化縣",
            "大埔鄉": "嘉義縣",
            "大埤鄉": "雲林縣",
            "大寮區": "高雄市",
            "大村鄉": "彰化縣",
            "大林鎮": "嘉義縣",
            "大樹區": "高雄市",
            "大武鄉": "台東縣",
            "大湖鄉": "苗栗縣",
            "大溪區": "桃園市",
            "大甲區": "台中市",
            "大社區": "高雄市",
            "大肚區": "台中市",
            "大里區": "台中市",
            "大雅區": "台中市",
            "太保市": "嘉義縣",
            "太平區": "台中市",
            "太麻里鄉": "台東縣",
            "學甲區": "台南市",
            "安南區": "台南市",
            "安定區": "台南市",
            "安平區": "台南市",
            "安樂區": "基隆市",
            "官田區": "台南市",
            "宜蘭市": "宜蘭縣",
            "富里鄉": "花蓮縣",
            "寶山鄉": "新竹縣",
            "將軍區": "台南市",
            "小港區": "高雄市",
            "尖石鄉": "新竹縣",
            "屏東市": "屏東縣",
            "山上區": "台南市",
            "岡山區": "高雄市",
            "峨眉鄉": "新竹縣",
            "崁頂鄉": "屏東縣",
            "崙背鄉": "雲林縣",
            "左營區": "高雄市",
            "左鎮區": "台南市",
            "布袋鎮": "嘉義縣",
            "平溪區": "新北市",
            "平鎮區": "桃園市",
            "延平鄉": "台東縣",
            "彌陀區": "高雄市",
            "彰化市": "彰化縣",
            "後壁區": "台南市",
            "後龍鎮": "苗栗縣",
            "復興區": "桃園市",
            "恆春鎮": "屏東縣",
            "成功鎮": "台東縣",
            "文山區": "台北市",
            "斗六市": "雲林縣",
            "斗南鎮": "雲林縣",
            "新化區": "台南市",
            "新園鄉": "屏東縣",
            "新城鄉": "花蓮縣",
            "新埔鎮": "新竹縣",
            "新埤鄉": "屏東縣",
            "新屋區": "桃園市",
            "新市區": "台南市",
            "新店區": "新北市",
            "新港鄉": "嘉義縣",
            "新營區": "台南市",
            "新社區": "台中市",
            "新興區": "高雄市",
            "新莊區": "新北市",
            "新豐鄉": "新竹縣",
            "旗山區": "高雄市",
            "旗津區": "高雄市",
            "春日鄉": "屏東縣",
            "暖暖區": "基隆市",
            "望安鄉": "澎湖縣",
            "朴子市": "嘉義縣",
            "杉林區": "高雄市",
            "東勢區": "台中市",
            "東勢鄉": "雲林縣",
            "東山區": "台南市",
            "東引鄉": "連江縣",
            "東河鄉": "台東縣",
            "東港鎮": "屏東縣",
            "東石鄉": "嘉義縣",
            "松山區": "台北市",
            "板橋區": "新北市",
            "枋寮鄉": "屏東縣",
            "枋山鄉": "屏東縣",
            "林內鄉": "雲林縣",
            "林口區": "新北市",
            "林園區": "高雄市",
            "林邊鄉": "屏東縣",
            "柳營區": "台南市",
            "桃園區": "桃園市",
            "桃源區": "高雄市",
            "梅山鄉": "嘉義縣",
            "梓官區": "高雄市",
            "梧棲區": "台中市",
            "楊梅區": "桃園市",
            "楠梓區": "高雄市",
            "楠西區": "台南市",
            "樹林區": "新北市",
            "橋頭區": "高雄市",
            "橫山鄉": "新竹縣",
            "歸仁區": "台南市",
            "民雄鄉": "嘉義縣",
            "水上鄉": "嘉義縣",
            "水林鄉": "雲林縣",
            "水里鄉": "南投縣",
            "永和區": "新北市",
            "永安區": "高雄市",
            "永康區": "台南市",
            "永靖鄉": "彰化縣",
            "汐止區": "新北市",
            "池上鄉": "台東縣",
            "沙鹿區": "台中市",
            "泰安鄉": "苗栗縣",
            "泰山區": "新北市",
            "泰武鄉": "屏東縣",
            "海端鄉": "台東縣",
            "淡水區": "新北市",
            "深坑區": "新北市",
            "清水區": "台中市",
            "湖內區": "高雄市",
            "湖口鄉": "新竹縣",
            "湖西鄉": "澎湖縣",
            "溪口鄉": "嘉義縣",
            "溪州鄉": "彰化縣",
            "溪湖鎮": "彰化縣",
            "滿州鄉": "屏東縣",
            "潭子區": "台中市",
            "潮州鎮": "屏東縣",
            "烈嶼鄉": "金門縣",
            "烏來區": "新北市",
            "烏坵鄉": "金門縣",
            "烏日區": "台中市",
            "燕巢區": "高雄市",
            "牡丹鄉": "屏東縣",
            "獅子鄉": "屏東縣",
            "獅潭鄉": "苗栗縣",
            "玉井區": "台南市",
            "玉里鎮": "花蓮縣",
            "琉球鄉": "屏東縣",
            "瑞穗鄉": "花蓮縣",
            "瑞芳區": "新北市",
            "瑪家鄉": "屏東縣",
            "田中鎮": "彰化縣",
            "田寮區": "高雄市",
            "田尾鄉": "彰化縣",
            "甲仙區": "高雄市",
            "番路鄉": "嘉義縣",
            "白沙鄉": "澎湖縣",
            "白河區": "台南市",
            "石岡區": "台中市",
            "石碇區": "新北市",
            "石門區": "新北市",
            "礁溪鄉": "宜蘭縣",
            "社頭鄉": "彰化縣",
            "神岡區": "台中市",
            "福興鄉": "彰化縣",
            "秀林鄉": "花蓮縣",
            "秀水鄉": "彰化縣",
            "竹北市": "新竹縣",
            "竹南鎮": "苗栗縣",
            "竹塘鄉": "彰化縣",
            "竹山鎮": "南投縣",
            "竹崎鄉": "嘉義縣",
            "竹東鎮": "新竹縣",
            "竹田鄉": "屏東縣",
            "綠島鄉": "台東縣",
            "線西鄉": "彰化縣",
            "羅東鎮": "宜蘭縣",
            "美濃區": "高雄市",
            "義竹鄉": "嘉義縣",
            "芎林鄉": "新竹縣",
            "芬園鄉": "彰化縣",
            "花壇鄉": "彰化縣",
            "花蓮市": "花蓮縣",
            "芳苑鄉": "彰化縣",
            "苑裡鎮": "苗栗縣",
            "苓雅區": "高雄市",
            "苗栗市": "苗栗縣",
            "茂林區": "高雄市",
            "茄萣區": "高雄市",
            "草屯鎮": "南投縣",
            "莒光鄉": "連江縣",
            "莿桐鄉": "雲林縣",
            "萬丹鄉": "屏東縣",
            "萬巒鄉": "屏東縣",
            "萬榮鄉": "花蓮縣",
            "萬華區": "台北市",
            "萬里區": "新北市",
            "蘆洲區": "新北市",
            "蘆竹區": "桃園市",
            "蘇澳鎮": "宜蘭縣",
            "蘭嶼鄉": "台東縣",
            "虎尾鎮": "雲林縣",
            "褒忠鄉": "雲林縣",
            "西屯區": "台中市",
            "西嶼鄉": "澎湖縣",
            "西港區": "台南市",
            "西湖鄉": "苗栗縣",
            "西螺鎮": "雲林縣",
            "觀音區": "桃園市",
            "豐原區": "台中市",
            "豐濱鄉": "花蓮縣",
            "貢寮區": "新北市",
            "路竹區": "高雄市",
            "車城鄉": "屏東縣",
            "通霄鎮": "苗栗縣",
            "造橋鄉": "苗栗縣",
            "達仁鄉": "台東縣",
            "那瑪夏區": "高雄市",
            "里港鄉": "屏東縣",
            "金城鎮": "金門縣",
            "金寧鄉": "金門縣",
            "金山區": "新北市",
            "金峰鄉": "台東縣",
            "金沙鎮": "金門縣",
            "金湖鎮": "金門縣",
            "銅鑼鄉": "苗栗縣",
            "長治鄉": "屏東縣",
            "長濱鄉": "台東縣",
            "關山鎮": "台東縣",
            "關廟區": "台南市",
            "關西鎮": "新竹縣",
            "阿蓮區": "高雄市",
            "阿里山鄉": "嘉義縣",
            "集集鎮": "南投縣",
            "雙溪區": "新北市",
            "霧峰區": "台中市",
            "霧臺鄉": "屏東縣",
            "頭份市": "苗栗縣",
            "頭城鎮": "宜蘭縣",
            "頭屋鄉": "苗栗縣",
            "香山區": "新竹市",
            "馬公市": "澎湖縣",
            "高樹鄉": "屏東縣",
            "魚池鄉": "南投縣",
            "鳥松區": "高雄市",
            "鳳山區": "高雄市",
            "鳳林鎮": "花蓮縣",
            "鶯歌區": "新北市",
            "鹽埔鄉": "屏東縣",
            "鹽埕區": "高雄市",
            "鹽水區": "台南市",
            "鹿港鎮": "彰化縣",
            "鹿草鄉": "嘉義縣",
            "鹿谷鄉": "南投縣",
            "鹿野鄉": "台東縣",
            "麟洛鄉": "屏東縣",
            "麥寮鄉": "雲林縣",
            "麻豆區": "台南市",
            "鼓山區": "高雄市",
            "龍井區": "台中市",
            "龍崎區": "台南市",
            "龍潭區": "桃園市",
            "龜山區": "桃園市",
        },
        "ambiguous": frozenset({"中山區", "中正區", "信義區", "北區", "南區", "大安區", "東區", "西區"}),
    },
    "US": {
        "tier1": {
            "Alabama": (32.377, -86.301),
            "Alaska": (61.218, -149.9),
            "Arizona": (33.448, -112.074),
            "Arkansas": (34.746, -92.29),
            "California": (38.582, -121.494),
            "Colorado": (39.739, -104.99),
            "Connecticut": (41.764, -72.682),
            "Delaware": (39.158, -75.524),
            "District of Columbia": (38.907, -77.037),
            "Florida": (30.438, -84.281),
            "Georgia": (33.749, -84.388),
            "Hawaii": (21.307, -157.858),
            "Idaho": (43.615, -116.202),
            "Illinois": (39.798, -89.644),
            "Indiana": (39.768, -86.158),
            "Iowa": (41.591, -93.604),
            "Kansas": (39.048, -95.678),
            "Kentucky": (38.204, -84.874),
            "Louisiana": (30.451, -91.187),
            "Maine": (44.307, -69.782),
            "Maryland": (38.979, -76.492),
            "Massachusetts": (42.36, -71.058),
            "Michigan": (42.734, -84.556),
            "Minnesota": (44.954, -93.09),
            "Mississippi": (32.299, -90.185),
            "Missouri": (38.579, -92.173),
            "Montana": (46.586, -112.018),
            "Nebraska": (40.808, -96.7),
            "Nevada": (39.164, -119.767),
            "New Hampshire": (43.207, -71.538),
            "New Jersey": (40.22, -74.77),
            "New Mexico": (35.687, -105.938),
            "New York": (42.652, -73.757),
            "North Carolina": (35.78, -78.639),
            "North Dakota": (46.809, -100.784),
            "Ohio": (39.961, -82.999),
            "Oklahoma": (35.468, -97.516),
            "Oregon": (44.938, -123.03),
            "Pennsylvania": (40.264, -76.884),
            "Rhode Island": (41.824, -71.413),
            "South Carolina": (34.001, -81.035),
            "South Dakota": (44.368, -100.351),
            "Tennessee": (36.163, -86.781),
            "Texas": (30.267, -97.743),
            "Utah": (40.761, -111.891),
            "Vermont": (44.26, -72.575),
            "Virginia": (37.541, -77.436),
            "Washington": (47.038, -122.901),
            "West Virginia": (38.337, -81.612),
            "Wisconsin": (43.074, -89.384),
            "Wyoming": (41.14, -104.82),
        },
        "tier2_to_tier1": {
            "Aberdeen": "South Dakota",
            "Akron": "Ohio",
            "Albany": "New York",
            "Albuquerque": "New Mexico",
            "Alexandria": "Virginia",
            "Allentown": "Pennsylvania",
            "Anaheim": "California",
            "Anchorage": "Alaska",
            "Ann Arbor": "Michigan",
            "Annapolis": "Maryland",
            "Appleton": "Wisconsin",
            "Athens": "Georgia",
            "Atlanta": "Georgia",
            "Austin": "Texas",
            "Bakersfield": "California",
            "Baltimore": "Maryland",
            "Bangor": "Maine",
            "Baton Rouge": "Louisiana",
            "Beaverton": "Oregon",
            "Bend": "Oregon",
            "Billings": "Montana",
            "Biloxi": "Mississippi",
            "Birmingham": "Alabama",
            "Bismarck": "North Dakota",
            "Boise": "Idaho",
            "Boston": "Massachusetts",
            "Boulder": "Colorado",
            "Bowling Green": "Kentucky",
            "Bozeman": "Montana",
            "Bridgeport": "Connecticut",
            "Broken Arrow": "Oklahoma",
            "Buffalo": "New York",
            "Burlington": "Vermont",
            "Cambridge": "Massachusetts",
            "Cape Coral": "Florida",
            "Carmel": "Indiana",
            "Casper": "Wyoming",
            "Cedar Rapids": "Iowa",
            "Chandler": "Arizona",
            "Charlotte": "North Carolina",
            "Chattanooga": "Tennessee",
            "Chesapeake": "Virginia",
            "Cheyenne": "Wyoming",
            "Chicago": "Illinois",
            "Cincinnati": "Ohio",
            "Clarksville": "Tennessee",
            "Cleveland": "Ohio",
            "Colorado Springs": "Colorado",
            "Concord": "New Hampshire",
            "Corpus Christi": "Texas",
            "Covington": "Kentucky",
            "Cranston": "Rhode Island",
            "Dallas": "Texas",
            "Davenport": "Iowa",
            "Dayton": "Ohio",
            "Denver": "Colorado",
            "Des Moines": "Iowa",
            "Detroit": "Michigan",
            "Duluth": "Minnesota",
            "Durham": "North Carolina",
            "Edison": "New Jersey",
            "Edmond": "Oklahoma",
            "El Paso": "Texas",
            "Elizabeth": "New Jersey",
            "Erie": "Pennsylvania",
            "Eugene": "Oregon",
            "Evansville": "Indiana",
            "Everett": "Washington",
            "Fairbanks": "Alaska",
            "Fargo": "North Dakota",
            "Fort Collins": "Colorado",
            "Fort Lauderdale": "Florida",
            "Fort Smith": "Arkansas",
            "Fort Wayne": "Indiana",
            "Fort Worth": "Texas",
            "Frederick": "Maryland",
            "Fresno": "California",
            "Gillette": "Wyoming",
            "Glendale": "Arizona",
            "Grand Forks": "North Dakota",
            "Grand Island": "Nebraska",
            "Grand Rapids": "Michigan",
            "Great Falls": "Montana",
            "Green Bay": "Wisconsin",
            "Greensboro": "North Carolina",
            "Greenville": "South Carolina",
            "Gresham": "Oregon",
            "Gulfport": "Mississippi",
            "Harrisburg": "Pennsylvania",
            "Hartford": "Connecticut",
            "Hattiesburg": "Mississippi",
            "Helena": "Montana",
            "Henderson": "Nevada",
            "Hialeah": "Florida",
            "Hilo": "Hawaii",
            "Honolulu": "Hawaii",
            "Houston": "Texas",
            "Huntington": "West Virginia",
            "Huntsville": "Alabama",
            "Idaho Falls": "Idaho",
            "Independence": "Missouri",
            "Indianapolis": "Indiana",
            "Iowa City": "Iowa",
            "Irvine": "California",
            "Jackson": "Mississippi",
            "Jacksonville": "Florida",
            "Jersey City": "New Jersey",
            "Joliet": "Illinois",
            "Juneau": "Alaska",
            "Kailua": "Hawaii",
            "Kapolei": "Hawaii",
            "Kenosha": "Wisconsin",
            "Knoxville": "Tennessee",
            "Lafayette": "Louisiana",
            "Lake Charles": "Louisiana",
            "Lakewood": "Colorado",
            "Lansing": "Michigan",
            "Laramie": "Wyoming",
            "Laredo": "Texas",
            "Las Cruces": "New Mexico",
            "Las Vegas": "Nevada",
            "Lewiston": "Maine",
            "Lexington": "Kentucky",
            "Lincoln": "Nebraska",
            "Little Rock": "Arkansas",
            "Long Beach": "California",
            "Los Angeles": "California",
            "Louisville": "Kentucky",
            "Lowell": "Massachusetts",
            "Macon": "Georgia",
            "Madison": "Wisconsin",
            "Manchester": "New Hampshire",
            "Memphis": "Tennessee",
            "Meridian": "Idaho",
            "Mesa": "Arizona",
            "Miami": "Florida",
            "Middletown": "Delaware",
            "Milwaukee": "Wisconsin",
            "Minneapolis": "Minnesota",
            "Minot": "North Dakota",
            "Missoula": "Montana",
            "Mobile": "Alabama",
            "Montgomery": "Alabama",
            "Montpelier": "Vermont",
            "Morgantown": "West Virginia",
            "Myrtle Beach": "South Carolina",
            "Nampa": "Idaho",
            "Naperville": "Illinois",
            "Naples": "Florida",
            "Nashua": "New Hampshire",
            "Nashville": "Tennessee",
            "New Haven": "Connecticut",
            "New Orleans": "Louisiana",
            "New Rochelle": "New York",
            "New York City": "New York",
            "Norfolk": "Virginia",
            "Norman": "Oklahoma",
            "North Charleston": "South Carolina",
            "North Las Vegas": "Nevada",
            "Oakland": "California",
            "Ogden": "Utah",
            "Oklahoma City": "Oklahoma",
            "Olathe": "Kansas",
            "Olympia": "Washington",
            "Omaha": "Nebraska",
            "Orlando": "Florida",
            "Overland Park": "Kansas",
            "Owensboro": "Kentucky",
            "Parkersburg": "West Virginia",
            "Paterson": "New Jersey",
            "Pawtucket": "Rhode Island",
            "Peoria": "Illinois",
            "Philadelphia": "Pennsylvania",
            "Phoenix": "Arizona",
            "Pierre": "South Dakota",
            "Pittsburgh": "Pennsylvania",
            "Plano": "Texas",
            "Pocatello": "Idaho",
            "Providence": "Rhode Island",
            "Provo": "Utah",
            "Quincy": "Massachusetts",
            "Racine": "Wisconsin",
            "Raleigh": "North Carolina",
            "Rapid City": "South Dakota",
            "Reading": "Pennsylvania",
            "Reno": "Nevada",
            "Richmond": "Virginia",
            "Rio Rancho": "New Mexico",
            "Riverside": "California",
            "Rockford": "Illinois",
            "Rockville": "Maryland",
            "Rutland": "Vermont",
            "Sacramento": "California",
            "Salem": "Oregon",
            "Salt Lake City": "Utah",
            "San Antonio": "Texas",
            "San Diego": "California",
            "San Francisco": "California",
            "San Jose": "California",
            "Santa Ana": "California",
            "Santa Fe": "New Mexico",
            "Savannah": "Georgia",
            "Scottsdale": "Arizona",
            "Seattle": "Washington",
            "Shreveport": "Louisiana",
            "Silver Spring": "Maryland",
            "Sioux City": "Iowa",
            "Sioux Falls": "South Dakota",
            "South Bend": "Indiana",
            "South Burlington": "Vermont",
            "Southaven": "Mississippi",
            "Sparks": "Nevada",
            "Spokane": "Washington",
            "Springdale": "Arkansas",
            "St. George": "Utah",
            "St. Louis": "Missouri",
            "St. Paul": "Minnesota",
            "St. Petersburg": "Florida",
            "Stamford": "Connecticut",
            "Sterling Heights": "Michigan",
            "Stockton": "California",
            "Syracuse": "New York",
            "Tacoma": "Washington",
            "Tallahassee": "Florida",
            "Tampa": "Florida",
            "Toledo": "Ohio",
            "Topeka": "Kansas",
            "Trenton": "New Jersey",
            "Tucson": "Arizona",
            "Tulsa": "Oklahoma",
            "Tuscaloosa": "Alabama",
            "Vancouver": "Washington",
            "Virginia Beach": "Virginia",
            "Warren": "Michigan",
            "Warwick": "Rhode Island",
            "Washington": "District of Columbia",
            "Wasilla": "Alaska",
            "Waterbury": "Connecticut",
            "West Valley City": "Utah",
            "Wichita": "Kansas",
            "Wilmington": "Delaware",
            "Winston-Salem": "North Carolina",
            "Worcester": "Massachusetts",
            "Yonkers": "New York",
        },
        "ambiguous": frozenset({"Arlington", "Augusta", "Aurora", "Bellevue", "Bloomington", "Charleston", "Columbia", "Columbus", "Dover", "Fayetteville", "Kansas City", "Newark", "Portland", "Rochester", "Springfield"}),
    },
}
