#!/usr/bin/env python3
"""Build the ordered, demo-free SQL bundle for a new production Supabase project."""
from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SQL_DIR = ROOT / "supabase" / "sql"
DEFAULT_OUT = ROOT / "dist" / "supabase" / "munea_production_bootstrap.sql"

MIGRATIONS = (
    "001_initial_munea_schema.sql",
    "003_analytics_admin_foundation.sql",
    "004_ai_memory_service_foundation.sql",
    "005_companion_persona_layer.sql",
    "006_billing_credits_foundation.sql",
    "007_family_cloud_state_foundation.sql",
    "008_family_vitals_state.sql",
    "009_perception_snapshot_daily_briefing.sql",
    "010_realtime_call_control.sql",
    "011_family_invitation_integrity.sql",
    "011_free_signup_trial_policy.sql",
    "012_production_security_hardening.sql",
    "013_current_app_billing_policy.sql",
)


def build() -> str:
    missing = [name for name in MIGRATIONS if not (SQL_DIR / name).is_file()]
    if missing:
        raise SystemExit("Missing migration files: " + ", ".join(missing))

    sections = [
        "-- Munea production Supabase bootstrap",
        "-- Generated by scripts/build_supabase_production_bundle.py",
        "-- Demo bootstrap 002_demo_bootstrap.sql is intentionally excluded.",
        "",
    ]
    for name in MIGRATIONS:
        content = (SQL_DIR / name).read_text(encoding="utf-8-sig").strip()
        digest = hashlib.sha256(content.encode("utf-8")).hexdigest()[:16]
        sections.extend((
            "-- ============================================================================",
            f"-- BEGIN {name} sha256:{digest}",
            "-- ============================================================================",
            content,
            f"-- END {name}",
            "",
        ))
    return "\n".join(sections).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--check", action="store_true", help="Verify an existing bundle is current")
    args = parser.parse_args()

    expected = build()
    output = args.out.resolve()
    if args.check:
        if not output.is_file() or output.read_text(encoding="utf-8") != expected:
            raise SystemExit(f"Production bundle is missing or stale: {output}")
        print(f"Production Supabase bundle is current: {output}")
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(expected, encoding="utf-8", newline="\n")
    print(f"Production Supabase bundle written: {output}")
    print("Migrations: " + ", ".join(MIGRATIONS))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
