#!/usr/bin/env python3
"""Build the idempotent 008-013 upgrade for the current Sydney project."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SQL_DIR = ROOT / "supabase" / "sql"
DEFAULT_OUT = ROOT / "dist" / "supabase" / "munea_launch_upgrade_008_013.sql"

MIGRATIONS = (
    "008_family_vitals_state.sql",
    "009_perception_snapshot_daily_briefing.sql",
    "010_realtime_call_control.sql",
    "011_family_invitation_integrity.sql",
    "011_free_signup_trial_policy.sql",
    "012_production_security_hardening.sql",
    "013_current_app_billing_policy.sql",
)


def build() -> str:
    missing = [name for name in MIGRATIONS if not (SQL_DIR / name).is_file()]
    if missing:
        raise SystemExit("Missing migration files: " + ", ".join(missing))

    sections = [
        "-- Munea launch upgrade for an existing 001-007 project",
        "-- Generated by scripts/build_supabase_launch_upgrade.py",
        "-- Apply once in Supabase SQL Editor, then verify Gateway /health.",
        "",
    ]
    for name in MIGRATIONS:
        content = (SQL_DIR / name).read_text(encoding="utf-8-sig").strip()
        digest = hashlib.sha256(content.encode("utf-8")).hexdigest()[:16]
        sections.extend((
            "-- ============================================================================",
            f"-- BEGIN {name} sha256:{digest}",
            "-- ============================================================================",
            content,
            f"-- END {name}",
            "",
        ))
    return "\n".join(sections).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    expected = build()
    output = args.out.resolve()
    if args.check:
        if not output.is_file() or output.read_text(encoding="utf-8") != expected:
            raise SystemExit(f"Launch upgrade bundle is missing or stale: {output}")
        print(f"Launch upgrade bundle is current: {output}")
        return 0

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(expected, encoding="utf-8", newline="\n")
    print(f"Launch upgrade bundle written: {output}")
    print("Migrations: " + ", ".join(MIGRATIONS))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
